import { useLoader, Canvas } from "react-three-fiber"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"
import ReactDOM from 'react-dom'
import React, { Suspense, useState, useRef } from 'react'
import { OrbitControls, Box } from 'drei'
import { useGLTF } from '@react-three/drei/useGLTF'
import { VRCanvas, DefaultXRControllers, Hover } from 'react-xr'
// import Chessboard from './Chessboard'
import './styles.css'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
function Chessboard(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chessboard/model.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[-0.64, -0.50, -0.10]}>
      <mesh material={materials.BlocksPaper} geometry={nodes['node_MeshObject1316465664-PolyPaper21'].geometry} />
    </group>
  )
}

function Knight(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/knight/model.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0.13, 1.25, -1.04]} scale={[0.5, 0.5, 0.5]}>
      <mesh material={materials.BlocksPaper} geometry={nodes['node_MeshObject-1328424064-PolyPaper23'].geometry} />
    </group>
  )
}

const App = () => {
  // const [isHovered, setIsHovered] = useState(false)
  // const color = isHovered ? 'blue' : '#e23'

  return (
    <VRCanvas>
      <ambientLight />
      <spotLight />

      <OrbitControls />

      {/* <Hover onChange={setIsHovered}>
        <Box position={[0, 0.8, -1]} scale={[0.3, 0.3, 0.3]}>
          <meshStandardMaterial color={color} />
        </Box>
      </Hover> */}

      <Suspense fallback={null}>
        <Chessboard />
        <Knight />
      </Suspense>
      <DefaultXRControllers />
    </VRCanvas>
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
