import { useLoader, Canvas } from "react-three-fiber"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"
import ReactDOM from 'react-dom'
import React, { Suspense, useState, useRef } from 'react'
import { OrbitControls, Box } from 'drei'
import { useGLTF } from '@react-three/drei/useGLTF'
import { VRCanvas, DefaultXRControllers, Hover } from 'react-xr'
// import Chessboard from './Chessboard'
import './styles.css'

// function Chessboard() {
//   // Load the gltf file
//   const { nodes, materials } = useLoader(GLTFLoader, "/chessboard.gltf")
//   // Fetch some reactive state
//   const model = useRef()

//   return (
//     <mesh dispose={null} scale={[0.1, 0.1, 0.1]}>
//       <group ref={model} position={[-0.05, 0.37, 0.3]} scale={[0.15, 0.15, 0.15]}>
//         <group rotation={[1.88, -0.35, 2.32]} scale={[2.97, 2.97, 2.97]}>
//           <primitive object={nodes.Bone} />
//           <skinnedMesh castShadow receiveShadow material={materials.glove} material-roughness={1} geometry={nodes.arm.geometry} skeleton={nodes.arm.skeleton} />
//         </group>
//         <group rotation={[0, -0.04, 0]} scale={[141.94, 141.94, 141.94]}>
//           <mesh castShadow receiveShadow material={materials.wood} geometry={nodes.mesh_0.geometry} />
//         </group>
//       </group>
//     </mesh>
//   )
// }

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
function Chessboard(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chessboard/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.BlocksPaper} geometry={nodes['node_MeshObject1316465664-PolyPaper21'].geometry} />
    </group>
  )
}

const App = () => {
  // const [isHovered, setIsHovered] = useState(false)
  // const color = isHovered ? 'blue' : '#e23'

  return (
    <VRCanvas>
      <ambientLight />
      <spotLight />

      <OrbitControls />

      {/* <Hover onChange={setIsHovered}>
        <Box position={[0, 0.8, -1]} scale={[0.3, 0.3, 0.3]}>
          <meshStandardMaterial color={color} />
        </Box>
      </Hover> */}
      {/* <Chessboard position={[5, 0.8, -2]} scale={[1, 1, 1]}>
      </Chessboard> */}
      <Suspense fallback={null}>
        <Chessboard />
      </Suspense>
      <DefaultXRControllers />
    </VRCanvas>
  )
  
  // return (
  //   <Canvas>
  //     <Suspense fallback={null}>
  //       <Chessboard />
  //     </Suspense>
  //   </Canvas>
  // )
}

ReactDOM.render(<App />, document.getElementById('root'))
